-- ARCHIVED SCHEMA ENTRYPOINT
--
-- Dylan's Palace now uses Prisma migrations as the canonical database history.
-- Do not run the former array-based schema from this path: it conflicts with
-- relational product_images, product_sizes and product_variants tables.
--
-- Apply migrations in order from `prisma/migrations/` after taking a backup.
-- See `docs/operations/database-migration.md` for staging, verification and rollback.
